version: '3.8'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: bot
      MONGO_INITDB_ROOT_PASSWORD: bot
    volumes:
      - mongo-data:/data/db
  bot:
    image: ghcr.io/mikbot/hafalsch/bot:latest
    env_file:
      - .env
    environment:
      - "GAMES=l: ${guild_count} guilds,l: ${channel_count} twitch channels"
    depends_on:
      - mongo
    volumes:
      - ./plugins:/usr/app/plugins
volumes:
  mongo-data: { }
