name: "Library publishing"

on:
  push:
    branches:
      - main
    paths:
      - client-common/**
      - marudor-client/**
      - regenbogen-ice-client/**
      - träwelling-client/**

env:
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_KEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_KEY_PASSWORD }}
  JFROG_KEY: ${{ secrets.JFROG_KEY }}
  JFROG_USER: ${{ secrets.JFROG_USER }}

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: 18
      - name: Publish with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishAllPublicationsToMavenRepository
